import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`md:max-w-4xl md:h-full md:mx-auto md:my-6 md:border-2 md: border-red-300 md:rounded md:p-6   ${inter.className}`}>
        {children}
      </body>
    </html>
  );
}
